version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    mem_limit: 512m
    command: run docker_dev

  database:
    ports:
      - "3307:3306"
    mem_limit: 1G