### GET AUTHORIZATION
# @name login
POST {{$dotenv %API_URL}}/auth/login
Content-Type: application/json

{
    "username": "user_test",
    "password": "user_test"
}

### FOLLOW USER
POST {{$dotenv %API_URL}}/user/follow/dU_Qqsja9tAifYZQPWcSN
Content-Type: application/json
Authorization: Bearer {{login.response.body.data}}

### VIEW FOLLOWINGS
GET {{$dotenv %API_URL}}/user/test_user_id/following
Content-Type: application/json